### ISSUE TITLE
Multiple Images Should work in Canvas

### ISSUE THREAD

**Issue by abhisheknaiidu** [abhisheknaiidu/vue-konva-experiment#2]
Right only the first Image which is being uploaded works in Canva

**Comment by GuilhermeOliveiraCasagrande** [comment]
I have forked, downloaded and served at localhost and it can already add multiple images out of the box, so this issue should probably be closed.

**Comment by abhisheknaiidu** [comment]
Yea You're actually right, but it opens new issue #4 now 😅
